name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/client  # 프로젝트 디렉토리
            rm -rf node_modules
            /home/ubuntu/.nvm/versions/node/v18.20.8/bin/yarn cache clean
            sudo journalctl --vacuum-time=1d
            git pull origin main
            /home/ubuntu/.nvm/versions/node/v18.20.8/bin/yarn install --frozen-lockfile
            /home/ubuntu/.nvm/versions/node/v18.20.8/bin/yarn build
